modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/JensenJ-Modding/YouShallNotTick/issues"
license = "MIT License"

[[mods]]
modId = "youshallnottick"
version = "${version}"
displayName = "You Shall Not Tick"
authors = "JensenJ - Developer, NoahS - Artist"
description = '''
Disables unnecessary ticking for living entities.
'''
logoFile = "logo.png"

[[dependencies.youshallnottick]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.youshallnottick]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.youshallnottick]]
modId = "architectury"
mandatory = true
versionRange = "[8.2.91,)"
ordering = "AFTER"
side = "BOTH"