plugins {
    id 'com.github.johnrengelman.shadow'
}

apply from: 'https://raw.githubusercontent.com/JensenJ-Modding/Mod-Resources/refs/heads/main/1.20.1/Gradle/fabric-build.gradle'

repositories {
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven { url = "https://maven.createmod.net" } // Ponder
    maven { url = "https://mvn.devos.one/releases" } // Porting Lib (needed for ponder)
    maven {
        url "https://maven.jamieswhiteshirt.com/libs-release" // Reach Entity Attributes (needed for porting lib)
        content {
            includeGroup "com.jamieswhiteshirt"
        }
    }
}

dependencies {
    modImplementation("curse.maven:jade-324717:${fabric_jade_id}")
    //modImplementation(include("net.createmod.ponder:Ponder-Fabric-${minecraft_version}:${ponder_version}"))
}