# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.2.0
maven_group = net.youshallnottick
archives_name = youshallnottick
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1

# Multiplatform Dependencies
architectury_api_version = 9.2.14
mixin_extras_version = 0.4.1
ponder_version = 1.0.64

# Fabric Dependencies
fabric_loader_version = 0.16.9
fabric_api_version = 0.92.3
forge_config_api_port_version=8.0.0
night_config_version=3.6.5
mod_menu_version = 7.2.2
fabric_jade_id = 6106093

# Forge Dependencies
forge_version = 47.4.0
forge_jade_id = 6106101
flywheel_version = 1.0.2
