plugins {
    id 'com.github.johnrengelman.shadow'
}

apply from: 'https://raw.githubusercontent.com/JensenJ-Modding/Mod-Resources/refs/heads/main/1.20.1/Gradle/forge-build.gradle'

repositories {
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven { url = "https://maven.createmod.net" }
}

dependencies {
    modImplementation("curse.maven:jade-324717:${forge_jade_id}")
    modImplementation("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")
    include("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")
    include("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")
}