apply from: 'https://raw.githubusercontent.com/JensenJ-Modding/Mod-Resources/refs/heads/main/1.21.1/Gradle/common-build.gradle'

repositories {
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven { url = "https://maven.createmod.net" }
}

dependencies {
    modImplementation("curse.maven:jade-324717:${fabric_jade_id}")
    modImplementation("net.createmod.ponder:Ponder-Common-${minecraft_version}:${ponder_version}")
}
