modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/JensenJ-Modding/YouShallNotTick/issues"
license = "MIT License"

[[mods]]
modId = "youshallnottick"
version = "${version}"
displayName = "You Shall Not Tick"
authors = "JensenJ - Developer, NoahS - Artist"
description = '''
Disables unnecessary ticking for living entities.
'''
logoFile = "logo.png"

[[mixins]]
config="youshallnottick-common.mixins.json"

[[dependencies.youshallnottick]]
modId = "neoforge"
type="required"
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.youshallnottick]]
modId = "architectury"
type="required"
versionRange = "[11.1.13,)"
ordering = "AFTER"
side = "BOTH"