modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/JensenJ-Modding/YouShallNotTick/issues"
license = "MIT License"

[[mods]]
modId = "youshallnottick"
version = "${version}"
displayName = "You Shall Not Tick"
authors = "JensenJ - Developer, NoahS - Artist, Yame5 - Artist"
description = '''
Disables unnecessary ticking for living entities.
'''
logoFile = "logo.png"

[[dependencies.youshallnottick]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.youshallnottick]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.youshallnottick]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.youshallnottick]]
modId = "jade"
type = "optional"
versionRange = "[15.10.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.youshallnottick]]
modId = "ponder"
type = "optional"
versionRange = "[1.0.56,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "youshallnottick-neoforge.mixins.json"

[[mixins]]
config = "youshallnottick-common.mixins.json"