plugins {
    id 'com.gradleup.shadow'
}

apply from: 'https://raw.githubusercontent.com/JensenJ-Modding/Mod-Resources/refs/heads/main/1.21.1/Gradle/neoforge-build.gradle'

repositories {
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven { url = "https://maven.createmod.net" }
}

dependencies {
    modImplementation("curse.maven:jade-324717:${neoforge_jade_id}")
    modRuntimeOnly(include("net.createmod.ponder:Ponder-NeoForge-${minecraft_version}:${ponder_version}")) { transitive = false}
    modRuntimeOnly(include("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}"))
}