name: Testing

on:
  push:
    branches:
      - "1.20.1"
  pull_request:
  workflow_dispatch:

jobs:
  testing:
    uses: JensenJ-Modding/Mod-Resources/.github/workflows/testing-forge-fabric.yml@main
    with:
      gradle_version: "8.11"
      java_version: 17
      fabric_mods: "https://edge.forgecdn.net/files/5137/936/architectury-9.2.14-fabric.jar https://edge.forgecdn.net/files/5902/421/ForgeConfigAPIPort-v8.0.1-1.20.1-Fabric.jar"
      forge_mods: "https://edge.forgecdn.net/files/5137/938/architectury-9.2.14-forge.jar"